name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@develop
        with:
          commit_message: "test message"
          committer_username:  "gkr-bot"
          readme_path: 'README.md, readme2.md'
          committer_email: "gkr@tuta.io"
          user_agent: "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          max_post_count: "5"
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"


