name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Hashnode posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://theintrovertcoder.hashnode.dev/rss.xml"
          max_post_count: 3
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/cover_image/"
          item_exec: |
            post.description = post.description.replace(/<\/?[^>]+(>|$)/g, "").slice(0,100)
          template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="140px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date <br> $description...</td></tr></table>$newline'
          disable_html_encoding: true
