name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "test message"
          committer_username:  "gkr-bot"
          committer_email: "gkr@tuta.io"
          max_post_count: "5"
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"


