name: Keepalive
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  keepalive:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
      - uses: gautamkrishnar/keepalive-workflow@master 
