name: Latest blog post workflow
on:
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: test workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master 
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        with:
          comment_tag_name: "TEST"
          max_post_count: "4"
          feed_list: "https://49.232.199.67/feed/"
