name: Latest stack oveflow activity
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/4214976"
          template: "<tr><td>$title</td><td>$url</td></tr>"

