name: Latest blog post test
on:
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@AvinashMahanthi"
